class_name NRPlayer
extends RefCounted
## Corp/Runner player records. Port of game.core.player.

static func new_corp(user: Dictionary, c_identity: Dictionary, options: Dictionary, deck: Array, deck_id: Variant, c_quote: Variant) -> Dictionary:
	return {
		"aid": 0,
		"user": user,
		"identity": c_identity,
		"options": options,
		"basic-action-card": null,
		"deck": deck,
		"deck-id": deck_id,
		"hand": [],
		"discard": [],
		"scored": [],
		"rfg": [],
		"play-area": [],
		"current": [],
		"set-aside": [],
		"set-aside-tracking": {},
		"servers": {
			"hq": {"content": [], "ices": []},
			"rd": {"content": [], "ices": []},
			"archives": {"content": [], "ices": []},
		},
		"click": 0,
		"click-per-turn": 3,
		"credit": 5,
		"bad-publicity": {"base": 0, "additional": 0},
		"toast": [],
		"properties": {},
		"hand-size": {"base": 5, "total": 5},
		"agenda-point": 0,
		"agenda-point-req": 7,
		"keep": false,
		"quote": c_quote,
		"prompt": [],
		"prompt-state": null,
		"register": {},
		"locked": {},
		"selected": [],
	}


static func new_runner(user: Dictionary, r_identity: Dictionary, options: Dictionary, deck: Array, deck_id: Variant, r_quote: Variant) -> Dictionary:
	return {
		"aid": 0,
		"user": user,
		"identity": r_identity,
		"options": options,
		"basic-action-card": null,
		"deck": deck,
		"deck-id": deck_id,
		"hand": [],
		"discard": [],
		"scored": [],
		"rfg": [],
		"play-area": [],
		"current": [],
		"set-aside": [],
		"set-aside-tracking": {},
		"rig": {"facedown": [], "hardware": [], "program": [], "resource": []},
		"toast": [],
		"click": 0,
		"click-per-turn": 4,
		"credit": 5,
		"run-credit": 0,
		"properties": {},
		"link": 0,
		"tag": {"base": 0, "total": 0, "is-tagged": false},
		"memory": {"base": 4, "available": 4, "used": 0, "only-for": {}},
		"hand-size": {"base": 5, "total": 5},
		"agenda-point": 0,
		"agenda-point-req": 7,
		"rd-access-fn": "seq",
		"hq-access-fn": "shuffle",
		"brain-damage": 0,
		"keep": false,
		"quote": r_quote,
		"prompt": [],
		"prompt-state": null,
		"register": {},
		"locked": {},
		"selected": [],
	}
